apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
data:
  config.json: |  
    {
      "url": "https://profile-hunt.online"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  selector:
    matchLabels:
      app: front-ph
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: front-ph
    spec:
      containers:
        - name: frontph
          imagePullPolicy: Always
          image: tristancht/ph-front:main
          ports:
            - containerPort: 80
          volumeMounts:
            - name: front-volume
              mountPath: /usr/share/nginx/html/assets
      volumes:
        - name: front-volume
          configMap:
            name: front-config
            items:
            - key: config.json
              path : config.json
      nodeSelector:
          kubernetes.io/arch: arm64
---
kind: Service
apiVersion: v1
metadata:
  name: front-ph-service
spec:
  selector:
    app: front-ban
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-deploy-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: dev-ph.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-ph-service
            port:
              number: 80

